### ISSUE TITLE
Support for more than one model/data_object and JOINs (many-to-many relationship)

### ISSUE THREAD

**Issue by dumblob** [naiquevin/lookupy#2]
Are there any plans in extending this handy tiny library with support for multiple models/input_data_objects in conjunction with support for JOINs (especially the many-to-many relationship)?

**Comment by naiquevin** [comment]
No, I don't plan to add support for JOINs. The main objective of this lib was to make it simpler to work with data that one typically finds in the json responses of rest APIs (which is mostly denormalized anyway). But if you have a valid usecase for JOINs, do share it and feel free to extend it/send pull request :smile:

**Comment by dumblob** [comment]
Ok, understood.
